development:
  adapter: postgresql
  database: buildfor_premix_web_dev1
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000
  template: template0
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: buildfor_premix_web_test1
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000
  template: template0
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: buildfor_premix_web_prod1
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000
  template: template0
  username: postgres
  password: postgres